import LegalPage, { LegalSection } from "@/components/LegalPage";

const Terms = () => (
  <LegalPage title="Terms of Service" updated="October 8, 2026">
    <p className="text-[15px] leading-relaxed text-muted-foreground">
      By using Poko you agree to these terms. They're short, so please read them.
    </p>

    <LegalSection heading="What Poko is">
      <p>
        Poko is a free tool that uses AI to suggest dinner menus, shopping notes and a cooking timeline. It's
        provided as is, and features may change or stop at any time.
      </p>
    </LegalSection>

    <LegalSection heading="AI suggestions need your judgement">
      <p>
        Menus are generated by AI and can be wrong. Always check ingredients for allergies and dietary needs,
        cook food to safe temperatures and use your own judgement. Prices and savings are rough estimates.
      </p>
    </LegalSection>

    <LegalSection heading="Your account">
      <p>
        Keep your login secure and don't share your account. You're responsible for what happens under it.
      </p>
    </LegalSection>

    <LegalSection heading="Fair use">
      <p>
        Don't abuse the service: no automated requests or scraping, no attempts to break or overload it, and
        nothing illegal. We may limit or end access for anyone who does.
      </p>
    </LegalSection>

    <LegalSection heading="Third-party content">
      <p>
        Recipe videos come from YouTube and belong to their creators. We don't control them.
      </p>
    </LegalSection>

    <LegalSection heading="Liability">
      <p>
        To the extent the law allows, Poko isn't liable for any loss or harm from using the app or relying on
        its suggestions.
      </p>
    </LegalSection>

    <LegalSection heading="Changes">
      <p>We may update these terms. If you keep using Poko after a change, the new terms apply.</p>
    </LegalSection>
  </LegalPage>
);

export default Terms;
